# Generated by Django 4.2.30 on 2026-04-15 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_history', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(db_column='agent_id', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='agents.agent')),
                ('version', models.ForeignKey(db_column='version_id', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='agents.agentversion')),
            ],
            options={
                'db_table': 'agent_sessions',
            },
        ),
    ]
