# Generated by Django 4.2.30 on 2026-04-15 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('state_schema', models.JSONField(default=dict)),
                ('entry_node', models.CharField(blank=True, max_length=255, null=True)),
                ('exit_nodes', models.JSONField(default=list)),
                ('metadata', models.JSONField(db_column='metadata', default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agents',
            },
        ),
        migrations.CreateModel(
            name='AgentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('entry_node', models.CharField(blank=True, max_length=255, null=True)),
                ('exit_nodes', models.JSONField(default=list)),
                ('state_schema', models.JSONField(default=dict)),
                ('metadata', models.JSONField(db_column='metadata', default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(db_column='agent_id', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='agents.agent')),
                ('created_from_version', models.ForeignKey(blank=True, db_column='created_from_version_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forked_versions', to='agents.agentversion')),
            ],
            options={
                'db_table': 'agent_versions',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('functional', 'Functional'), ('llm_call', 'LLM Call'), ('communication', 'Communication')], max_length=30)),
                ('subtype', models.CharField(choices=[('python_inline', 'Python Inline'), ('api_call', 'API Call'), ('agent_call', 'Agent Call'), ('chat', 'Chat'), ('llm_agent', 'LLM Agent'), ('rabbitmq_message', 'RabbitMQ Message'), ('kafka', 'Kafka'), ('api', 'API')], default='python_inline', max_length=30)),
                ('config', models.JSONField(default=dict)),
                ('position_x', models.FloatField(default=0.0)),
                ('position_y', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(db_column='agent_id', on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='agents.agent')),
                ('version', models.ForeignKey(db_column='version_id', on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='agents.agentversion')),
            ],
            options={
                'db_table': 'nodes',
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_node_id', models.BigIntegerField()),
                ('target_node_id', models.BigIntegerField()),
                ('edge_type', models.CharField(choices=[('direct', 'Direct'), ('conditional', 'Conditional')], default='direct', max_length=20)),
                ('condition_config', models.JSONField(default=dict)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(db_column='agent_id', on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='agents.agent')),
                ('version', models.ForeignKey(db_column='version_id', on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='agents.agentversion')),
            ],
            options={
                'db_table': 'edges',
            },
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['status', 'created_at'], name='ix_agents_status_created_at'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['created_at'], name='ix_agents_created_at'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['agent', 'created_at'], name='ix_nodes_agent_created_at'),
        ),
        migrations.AddConstraint(
            model_name='node',
            constraint=models.UniqueConstraint(fields=('version', 'name'), name='uq_nodes_version_name'),
        ),
        migrations.AddConstraint(
            model_name='node',
            constraint=models.UniqueConstraint(fields=('agent', 'id'), name='uq_nodes_agent_id_id'),
        ),
        migrations.AddIndex(
            model_name='edge',
            index=models.Index(fields=['agent', 'source_node_id'], name='ix_edges_agent_source'),
        ),
        migrations.AddIndex(
            model_name='edge',
            index=models.Index(fields=['agent', 'target_node_id'], name='ix_edges_agent_target'),
        ),
        migrations.AddIndex(
            model_name='edge',
            index=models.Index(fields=['agent', 'created_at'], name='ix_edges_agent_created_at'),
        ),
        migrations.AddConstraint(
            model_name='agentversion',
            constraint=models.UniqueConstraint(fields=('agent', 'version_number'), name='uq_agent_versions_agent_version'),
        ),
    ]
