# Generated by Django 4.2.30 on 2026-04-24 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='entry_node',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='exit_nodes',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='state_schema',
        ),
        migrations.RemoveField(
            model_name='agentversion',
            name='metadata',
        ),
    ]
