# Generated by Django 4.2.30 on 2026-04-15 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent_sessions', '__first__'),
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('input_data', models.JSONField(default=dict)),
                ('output_data', models.JSONField(default=dict)),
                ('conversation_turn', models.JSONField(default=list)),
                ('state_snapshots', models.JSONField(default=list)),
                ('error', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(db_column='agent_id', on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='agents.agent')),
                ('session', models.ForeignKey(blank=True, db_column='session_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='agent_sessions.agentsession')),
                ('version', models.ForeignKey(blank=True, db_column='version_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='agents.agentversion')),
            ],
            options={
                'db_table': 'runs',
                'indexes': [models.Index(fields=['agent', 'started_at'], name='ix_runs_agent_started_at'), models.Index(fields=['status'], name='ix_runs_status')],
            },
        ),
    ]
