# Generated by Django 4.2.30 on 2026-04-16 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0001_initial'),
    ]

    operations = [
        # The run_status column is a native PostgreSQL ENUM created by SQLAlchemy.
        # Django's AlterField only updates metadata — we must extend the PG enum type manually.
        migrations.RunSQL(
            sql="ALTER TYPE run_status ADD VALUE IF NOT EXISTS 'interrupted';",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name='run',
            name='checkpoint_thread_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='resumed_from_run',
            field=models.ForeignKey(blank=True, db_column='resumed_from_run_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_runs', to='runs.run'),
        ),
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('interrupted', 'Interrupted')], default='pending', max_length=20),
        ),
    ]
