# Generated by Django 4.2.30 on 2026-04-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0004_run_interrupt_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
