# Generated by Django 4.2.30 on 2026-04-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0004_run_interrupt_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='review_metadata',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='sla_timeout_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
