# Generated by Django 4.2.30 on 2026-04-24 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0005_run_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='conversation_turn',
        ),
        migrations.RemoveField(
            model_name='run',
            name='input_data',
        ),
        migrations.RemoveField(
            model_name='run',
            name='output_data',
        ),
    ]
